[build]
builder = "nixpacks"

# Force Java 17
[build.nixpacksPlan]
providers = ["java"]

[build.nixpacksPlan.install]
packages = ["jdk17"]

[build.nixpacksPlan.build]
cmds = [
    "./gradlew build -x test"
]

[deploy]
start = "java -jar build/libs/*.jar"
